#!/bin/sh -ex

match-identities \
    --output "${IDENTITY_MATCHING_OUTPUT}" \
    --host "${IDENTITY_MATCHING_GITBASE_HOST}" \
    --port ${IDENTITY_MATCHING_GITBASE_PORT} \
    --user "${IDENTITY_MATCHING_GITBASE_USER}" \
    --password "${IDENTITY_MATCHING_GITBASE_PASSWORD}" \
    --external "${IDENTITY_MATCHING_EXTERNAL}" \
    --api-url "${IDENTITY_MATCHING_API_URL}" \
    --token "${IDENTITY_MATCHING_TOKEN}" \
    --max-identities "${IDENTITY_MATCHING_MAX_IDENTITIES}" \

parquet2sql.py \
       --db "postgresql://${IDENTITY_MATCHING_POSTGRES_USER}:${IDENTITY_MATCHING_POSTGRES_PASSWORD}@${IDENTITY_MATCHING_POSTGRES_HOST}:${IDENTITY_MATCHING_POSTGRES_PORT}/${IDENTITY_MATCHING_POSTGRES_DB}" \
       --parquet "${IDENTITY_MATCHING_OUTPUT}-identities.parquet" \
       --table "${IDENTITY_MATCHING_POSTGRES_IDENTITIES_TABLE}"

parquet2sql.py \
       --db "postgresql://${IDENTITY_MATCHING_POSTGRES_USER}:${IDENTITY_MATCHING_POSTGRES_PASSWORD}@${IDENTITY_MATCHING_POSTGRES_HOST}:${IDENTITY_MATCHING_POSTGRES_PORT}/${IDENTITY_MATCHING_POSTGRES_DB}" \
       --parquet "${IDENTITY_MATCHING_OUTPUT}-aliases.parquet" \
       --table "${IDENTITY_MATCHING_POSTGRES_ALIASES_TABLE}"