IGNORED_NAMES = set(map(lambda x: x.lower(), [
    "GitHub",
    "unknown",
    "AWS CodeStar",
    "root",
    "CodeStar Canary",
    "Unknown",
    "github username",
    "Your Name",
    "openshiftio-launchpad",
    "nodemcu-custom-build",
    "Commit Bot",
    "DevExpressExampleBot",
    "snyk-bot",
    "admin",
    "CocoaPodsBot",
    "dependabot[bot]",
    "Gerrit Code Review",
    "Ubuntu",
    "Deployment Bot (from Travis CI)",
    "Administrator",
    "Renovate Bot",
    "EC2 Default User",
    "whitesource-bolt-for-github[bot]",
    "greenkeeper[bot]",
    "Forestry.io",
    "Keks",
    "Facebook Github Bot",
    "gitbook-bot",
    "takagotch",
    "Eclipse Che test account",
    "default-name",
    "Weblate",
    "user",
    "Red Hat Developers Launcher",
    "regro-cf-autotick-bot",
    "vagrant",
    "android-build-merger",
    "jsDelivr Bot",
    "jenkins-x-bot",
    "Gerrit - the friendly Code Review server",
    "cran-robot",
    "BuildTools",
    "GitHub Enterprise",
    "Travis CI User",
    "The Codacy Badger",
    "Admin",
    "Hosted Weblate",
    "TensorFlower Gardener",
    "Student",
    "Kubernetes Prow Robot",
    "ImgBotApp",
    "UnofficialJuliaMirrorBot",
    "GNOME Translation Robot",
    "Mozilla Pontoon",
    "pyup-bot",
    "Mozilla-GitHub-Standards",
    "User",
    "student",
    "renovate[bot]",
    "Travis CI",
    "azure-pipelines[bot]",
    "System Administrator",
    "CppanBot",
    "StyleCI Bot",
    "fcc-mirror-bot",
    "JHipster Bot",
    "fossabot",
    "Copybara-Service",
    "reporobot",
    "system",
    "siteleaf",
    "codecademy",
    "travis",
    "anonymous",
]))
